// src/lib/search/commandRegistry.ts
// Data-driven command registry for SubhashOS command palette

import type { Command } from './types';

// Commands that need router/store access get their run() injected at render time.
// This registry defines the static metadata; actual execution is wired in CommandPalette.

export const COMMANDS: Command[] = [
  // ── Navigation ─────────────────────────────────────
  {
    id: 'home',
    label: 'Home',
    aliases: ['home', 'goto home', 'cd ~', 'cd /'],
    description: 'Navigate to the home desktop',
    category: 'navigation',
    icon: '🏠',
    keywords: ['home', 'main', 'desktop', 'landing'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => { /* wired at render */ },
  },
  {
    id: 'projects',
    label: 'Projects',
    aliases: ['projects', 'goto projects', 'cd /projects', 'open projects'],
    description: 'Browse all repositories and projects',
    category: 'navigation',
    icon: '📁',
    keywords: ['projects', 'repos', 'github', 'code'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'research',
    label: 'Research',
    aliases: ['research', 'goto research', 'cd /research', 'papers'],
    description: 'View IEEE publications and papers',
    category: 'navigation',
    icon: '🔬',
    keywords: ['research', 'papers', 'ieee', 'academic'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'resume',
    label: 'Resume',
    aliases: ['resume', 'goto resume', 'cd /resume', 'open resume', 'cv'],
    description: 'View interactive resume with ATS export',
    category: 'navigation',
    icon: '📄',
    keywords: ['resume', 'cv', 'hire', 'download'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'contact',
    label: 'Contact',
    aliases: ['contact', 'goto contact', 'email', 'reach out'],
    description: 'Get in touch with Subhash',
    category: 'navigation',
    icon: '✉️',
    keywords: ['contact', 'email', 'hire', 'message'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'download-resume',
    label: 'Download Resume',
    aliases: ['download resume', 'download cv', 'get resume'],
    description: 'Open resume page for PDF export',
    category: 'navigation',
    icon: '⬇️',
    keywords: ['download', 'pdf', 'export', 'resume'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },

  // ── Utility ─────────────────────────────────────────
  {
    id: 'help',
    label: 'Help',
    aliases: ['help', '?', 'commands', 'man'],
    description: 'Show all available commands, shortcuts, and Easter eggs',
    category: 'utility',
    icon: '❓',
    keywords: ['help', 'commands', 'guide', 'manual'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'shortcuts',
    label: 'Keyboard Shortcuts',
    aliases: ['shortcuts', 'keys', 'keybinds'],
    description: 'Show keyboard shortcut reference',
    category: 'utility',
    icon: '⌨️',
    keywords: ['shortcuts', 'keyboard', 'hotkeys'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'achievements',
    label: 'Achievements',
    aliases: ['achievements', 'badges', 'trophies'],
    description: 'View your unlocked Easter egg achievements',
    category: 'utility',
    icon: '🏆',
    keywords: ['achievements', 'badges', 'unlocked'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'clear',
    label: 'Clear',
    aliases: ['clear', 'cls'],
    description: 'Clear the palette and reset state',
    category: 'utility',
    icon: '🧹',
    keywords: ['clear', 'reset', 'clean'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },

  // ── System / Terminal ──────────────────────────────
  {
    id: 'whoami',
    label: 'whoami',
    aliases: ['whoami', 'who am i'],
    description: 'Display current user identity',
    category: 'system',
    icon: '👤',
    keywords: ['whoami', 'user', 'identity'],
    preview: 'subhash@subhashos — AI Engineer | DevOps Enthusiast | Linux User',
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => 'subhash@subhashos — AI Engineer | DevOps Enthusiast | Linux User',
  },
  {
    id: 'ls',
    label: 'ls',
    aliases: ['ls', 'dir', 'ls -la'],
    description: 'List directory contents',
    category: 'system',
    icon: '📂',
    keywords: ['ls', 'list', 'directory', 'files'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => [
      'drwxr-xr-x  projects/',
      'drwxr-xr-x  research/',
      'drwxr-xr-x  resume/',
      '-rw-r--r--  about.txt',
      '-rw-r--r--  skills.json',
      '-rw-r--r--  contact.cfg',
    ],
  },
  {
    id: 'cat-about',
    label: 'cat about.txt',
    aliases: ['cat about.txt', 'cat about', 'cat'],
    description: 'Display about file contents',
    category: 'system',
    icon: '📝',
    keywords: ['cat', 'about', 'read', 'file'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => [
      'AI Engineer & DevOps enthusiast.',
      'Building intelligent systems,',
      'automating infrastructure, and',
      "exploring AI's real-world impact.",
      '— Subhash R, Chennai, India',
    ],
  },
  {
    id: 'ping-subhash',
    label: 'ping subhash',
    aliases: ['ping subhash', 'ping'],
    description: 'Check if Subhash is reachable',
    category: 'system',
    icon: '📡',
    keywords: ['ping', 'network', 'latency', 'reach'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => [
      'PING subhash.dev (127.0.0.1): 56 data bytes',
      '64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.042ms',
      '64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.038ms',
      '64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.041ms',
      '--- subhash.dev ping statistics ---',
      '3 packets transmitted, 3 received, 0% packet loss',
      'round-trip min/avg/max = 0.038/0.040/0.042 ms',
      '✓ Subhash is online and ready to build.',
    ],
  },
  {
    id: 'ls-secrets',
    label: 'ls -la secrets/',
    aliases: ['ls -la secrets/', 'ls secrets', 'ls -la secrets'],
    description: 'Peek into the secrets directory',
    category: 'system',
    icon: '🔐',
    keywords: ['secrets', 'hidden', 'files', 'directory'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => [
      'total 42',
      'drwx------  2 subhash subhash 4096 May 29 2026 .',
      '-rw-------  1 subhash subhash  512 never-give-up.md',
      '-rw-------  1 subhash subhash  256 imposter-syndrome-cure.sh',
      '-rw-------  1 subhash subhash 1024 dream-projects.todo',
      '-rw-------  1 subhash subhash  128 .coffee-addiction.conf',
      '-rw-------  1 subhash subhash  404 meaning-of-life.txt (not found)',
      '-rwx------  1 subhash subhash 9999 anime-watchlist.json',
      '-rw-------  1 subhash subhash    1 bugs-in-production.log (empty!)',
    ],
  },
  {
    id: 'help-me',
    label: 'help me',
    aliases: ['help me', 'sos', 'send help'],
    description: 'Get help — navigates to contact page',
    category: 'system',
    icon: '🆘',
    keywords: ['help', 'contact', 'support', 'sos'],
    preview: 'Navigates to the contact page after a witty response',
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => [
      '> Analyzing your request...',
      '> Running emotional-support-daemon...',
      '> Diagnosis: You need to talk to a human.',
      "> Redirecting to Subhash's contact page...",
      '> Remember: every bug is just an undocumented feature. 🐛',
    ],
  },

  // ── Easter Egg Commands ────────────────────────────
  {
    id: 'noir',
    label: 'Noir Mode',
    aliases: ['noir', 'spidernoir', 'spider-noir'],
    description: 'Activate Spider-Noir grayscale mode with rain and quotes',
    category: 'easter-egg',
    icon: '🕷️',
    keywords: ['noir', 'spider', 'black', 'white', 'grayscale'],
    preview: '🎬 Cinematic Easter egg — turns site grayscale with noir atmosphere',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'binks',
    label: "Bink's Sake",
    aliases: ['binks', 'binkssake', "bink's sake"],
    description: 'Play the legendary pirate shanty',
    category: 'easter-egg',
    icon: '🏴‍☠️',
    keywords: ['binks', 'sake', 'pirate', 'one piece', 'shanty'],
    preview: '🎬 Hidden audio + pirate ship sailing animation',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'return-by-death',
    label: 'Return by Death',
    aliases: ['return-by-death', 'rbd', 'return by death'],
    description: 'Rewind time — replays the boot sequence',
    category: 'easter-egg',
    icon: '💀',
    keywords: ['return', 'death', 'rewind', 'rezero', 'boot'],
    preview: '🎬 Freezes animations, rewinds boot timeline, replays startup',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'satella',
    label: 'Satella',
    aliases: ['satella', 'i can return by death'],
    description: 'Summon the Witch of Envy',
    category: 'easter-egg',
    icon: '🌑',
    keywords: ['satella', 'witch', 'envy', 'rezero', 'shadow'],
    preview: '🎬 Cinematic dark overlay with shadow hands and video reveal',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'laugh-tale',
    label: 'Laugh Tale',
    aliases: ['laugh tale', 'laughtale'],
    description: 'Reach the final island — confetti celebration!',
    category: 'easter-egg',
    icon: '🏝️',
    keywords: ['laugh', 'tale', 'one piece', 'treasure', 'confetti'],
    preview: '🎬 Terminal message + custom tech-themed confetti rain',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'gear5',
    label: 'Gear 5',
    aliases: ['gear5', 'gear 5', 'gear5th', 'nika'],
    description: 'Activate Sun God Nika — pure joy!',
    category: 'easter-egg',
    icon: '☀️',
    keywords: ['gear', 'five', 'nika', 'sun', 'god', 'luffy'],
    preview: '🎬 White flash, bouncy UI, cloud particles',
    dangerLevel: 'cinematic',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'sudo-rm',
    label: 'sudo rm -rf /',
    aliases: ['sudo rm -rf /', 'sudo rm -rf', 'sudo rm'],
    description: 'The forbidden command (fake destructive)',
    category: 'easter-egg',
    icon: '💣',
    keywords: ['sudo', 'rm', 'delete', 'destroy', 'nuke'],
    preview: '⚠️ Fake destructive — panels collapse and restore',
    dangerLevel: 'fake-destructive',
    visibleInHelp: true,
    run: () => [
      '[sudo] password for subhash: ********',
      'rm: it is dangerous to operate recursively on "/"',
      'rm: use --no-preserve-root to override this failsafe',
      '...',
      'Just kidding. 😄 This is a portfolio, not a terminal.',
      'But respect for trying. Achievement unlocked! 🏆',
    ],
  },
  {
    id: 'vim',
    label: 'vim',
    aliases: ['vim', 'vi'],
    description: 'Open a fake Vim editor — can you exit?',
    category: 'easter-egg',
    icon: '📟',
    keywords: ['vim', 'vi', 'editor', 'exit'],
    preview: '🎬 Fake Vim session — type :q! or :wq to escape',
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },

  // ── Media ──────────────────────────────────────────
  {
    id: 'play',
    label: 'Play Music',
    aliases: ['play', 'play music'],
    description: 'Resume music playback',
    category: 'media',
    icon: '▶️',
    keywords: ['play', 'music', 'audio', 'resume'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'pause',
    label: 'Pause Music',
    aliases: ['pause', 'stop', 'pause music'],
    description: 'Pause music playback',
    category: 'media',
    icon: '⏸️',
    keywords: ['pause', 'stop', 'music', 'mute'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
  {
    id: 'next',
    label: 'Next Track',
    aliases: ['next', 'skip', 'next track'],
    description: 'Skip to next track',
    category: 'media',
    icon: '⏭️',
    keywords: ['next', 'skip', 'track', 'song'],
    dangerLevel: 'safe',
    visibleInHelp: true,
    run: () => {},
  },
];

export function findCommand(input: string): Command | null {
  const lower = input.toLowerCase().trim();
  return COMMANDS.find(
    (cmd) =>
      cmd.id === lower ||
      cmd.aliases.some((a) => a.toLowerCase() === lower)
  ) || null;
}

export function getAllCommands(): Command[] {
  return COMMANDS;
}

export function getVisibleCommands(): Command[] {
  return COMMANDS.filter((c) => c.visibleInHelp);
}

export function getCommandsByCategory(category: string): Command[] {
  return COMMANDS.filter((c) => c.category === category && c.visibleInHelp);
}
